/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sped;

import sped.ArduinoConnection.ArduinoConnectionResult;

/**
 *
 * @author edwinfinch
 */
public class OneDimensionSimulationWindow extends javax.swing.JFrame implements DataCollectorCallback {

    /**
     * Creates new form OneDimensionWindow
     */
    public OneDimensionSimulationWindow() {
        initComponents();
        
        ArduinoConnection arduinoConnection = new ArduinoConnection();

        ArduinoConnectionResult result = arduinoConnection.initialize();
        boolean connectedToArduino = (result == ArduinoConnectionResult.Success);
        System.out.println(connectedToArduino ? "Connected to Arduino." : ("Failed to connect: " + result.getMessage()));

        if(connectedToArduino){
            DataCollector collector = new DataCollector();
            collector.setDataCollectionCallback(this);
            arduinoConnection.setOnSerialListener(collector);
        }
    }
    
    @Override
    public void gotTravelThroughSensor(int sensorPin, long timeTravelled) {
        System.out.println("Got a pin travel through " + sensorPin + " with a time of " + timeTravelled + "ms.");
    }

    @Override
    public void gotSpeedThroughPole(boolean frontPole, double speedInCmPerSec, long timestamp) {
        System.out.println("Got a speed of " + speedInCmPerSec + "cm/sec on the " + (frontPole ? "front pole" : "back pole"));
        
        if(frontPole){
            initialSpeedLabel.setText("Initial speed: " + (speedInCmPerSec/100) + "m/s");
            initialTimeLabel.setText("Initial time: " + (double)(timestamp/1000));
        }
        else{
            finalSpeedLabel.setText("Final speed: " + (speedInCmPerSec/100) + "m/s");
            finalTimeLabel.setText("Final time: " + (double)(timestamp/1000));
        }
    }

    @Override
    public void gotAccelerationAndFriction(double accelerationInCmSquaredPerSec, double forceOfFriction, double coefficientOfFriction) {
        System.out.println("Got an acceleration of " + accelerationInCmSquaredPerSec + "cm/sec^2 with a force of friction of " + forceOfFriction + " and a coefficient of " + coefficientOfFriction);
        accelerationLabel.setText("Acceleration: " + accelerationInCmSquaredPerSec/100 + "m/s^2");
        forceOfFrictionLabel.setText("Force of friction: " + forceOfFriction + "N");
        coefficientOfFrictionLabel.setText("Coefficient of friction: " + coefficientOfFriction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        initialTimeLabel = new javax.swing.JLabel();
        initialSpeedLabel = new javax.swing.JLabel();
        finalTimeLabel = new javax.swing.JLabel();
        finalSpeedLabel = new javax.swing.JLabel();
        accelerationLabel = new javax.swing.JLabel();
        forceOfFrictionLabel = new javax.swing.JLabel();
        coefficientOfFrictionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("1D Acceleration");

        initialTimeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        initialTimeLabel.setText("Initial time: N/A");

        initialSpeedLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        initialSpeedLabel.setText("Initial speed: N/A");

        finalTimeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        finalTimeLabel.setText("Final time: N/A");

        finalSpeedLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        finalSpeedLabel.setText("Final speed: N/A");

        accelerationLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        accelerationLabel.setText("Acceleration: N/A");

        forceOfFrictionLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        forceOfFrictionLabel.setText("Force of friction: N/A");

        coefficientOfFrictionLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        coefficientOfFrictionLabel.setText("Coefficient of friction: N/A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(initialTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(initialSpeedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(finalTimeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(finalSpeedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(accelerationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(forceOfFrictionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(coefficientOfFrictionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(initialTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(initialSpeedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finalTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(finalSpeedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(accelerationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forceOfFrictionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(coefficientOfFrictionLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accelerationLabel;
    private javax.swing.JLabel coefficientOfFrictionLabel;
    private javax.swing.JLabel finalSpeedLabel;
    private javax.swing.JLabel finalTimeLabel;
    private javax.swing.JLabel forceOfFrictionLabel;
    private javax.swing.JLabel initialSpeedLabel;
    private javax.swing.JLabel initialTimeLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
